version: '3'
services:
  msa-mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: koscom
      MYSQL_ROOT_PASSWORD: koscom
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./data:/var/lib/mysql
