spring:
  devtools:
    livereload:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todo
    username: todo
    password: koscom
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/todo
#    username: todo
#    password: koscom

#spring:
#  data:
#    rest:
#      return-body-on-create: true
#      return-body-on-update: true
#      base-path: /api
#      default-page-size: 10

#spring:
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: ...

server:
  port: 8081
